### ISSUE TITLE
Podcasts 최신 데이터 수집에서 에러가 발생합니다. 

### ISSUE THREAD

**Issue by rorlab** [RORLabNew/rorla#120]
@seapy 님~

```
Started GET "/podcasts/grap" for 127.0.0.1 at 2014-10-08 08:57:30 +0900
Processing by PodcastsController#grap as JS
  Bulletin Load (0.2ms)  SELECT "bulletins".* FROM "bulletins"
  User Load (0.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
   (0.1ms)  SELECT COUNT(*) FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = ? AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 1]]
  Rendered shared/_flash_messages.html.erb (1.0ms)
  Rendered podcasts/grap.js.erb (7.0ms)
Completed 200 OK in 38ms (Views: 23.1ms | ActiveRecord: 0.3ms)
/Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/source/git.rb:188:in `rescue in load_spec_files': git://github.com/rorlab/docker_alias.git (at master) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/source/git.rb:185:in `load_spec_files'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/source/path.rb:92:in `local_specs'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/source/git.rb:155:in `specs'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/lazy_specification.rb:53:in `__materialize__'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/spec_set.rb:88:in `block in materialize'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/spec_set.rb:85:in `map!'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/definition.rb:132:in `specs'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/definition.rb:177:in `specs_for'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/definition.rb:166:in `requested_specs'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/environment.rb:18:in `requested_specs'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/runtime.rb:13:in `setup'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler.rb:121:in `setup'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.7.3/lib/bundler/setup.rb:17:in `<top (required)>'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/hyo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by seapy** [comment]
bundle install 이 잘못된 문제로 보이며 현재 동작하고 있어 이슈를 닫습니다
